name: MailBox
version: '${version}'
api-version: '1.21.6'
authors: [ ikafly144 ]
website: https://github.com/ikafly144/MailBox
bootstrapper: net.sabafly.mailBox.Bootstrapper
main: net.sabafly.mailBox.MailBox
loader: net.sabafly.mailBox.Loader
dependencies:
  server:
    Vault:
      required: false
      load: BEFORE
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
permissions:
  mailBox.admin:
    description: Allows the user to use all MailBox commands
    default: op
    children:
      mailbox.template: true
      mailbox.template.send: true
      mailbox.attachment.command: true
      mailbox.attachment.message: true
      mailbox.inbox.other: true
  mailBox.default:
    description: Allows the user to use MailBox
    default: true
    children:
      mailbox.inbox: true
      mailbox.send: true
      mailbox.attachment.item: true
      mailbox.attachment.vault: true
